### DISCUSSION TITLE
Option to change the streaming protocol

### DISCUSSION THREAD

**Discussion by AleksanderKruecken** [monkeymademe/CamUI#77] [Ideas]
It seems that http://myserver:8080/video_feed_0 is MJPEG which is older video compression format which results in larger file sizes and lower quality compared to formats like H.264 which Picamera2 library also supports.
According to Picamera2 library HLS stream and MPEG-DASH stream are also possible. 
Maybe you could add option for the user to choose the streamming protocol.
For example Frigate likes cameras with RTSP stream and I'm having trouble integrating this MJPEG into it (I'm struggling with go2rtc conversion from http to rtsp).

**Comment by monkeymademe** [comment]
After makerfaire next weekend, I am going to look into this...

**Comment by AleksanderKruecken** [comment]
I managed to get the stream into Frigate and create clips when person is detected with following frigate configuration if someone will have similar problem:
```
mqtt:
  host: 172.17.1.116
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: *****
  password: *****

detectors:
  cpu1:  # Name the detector (can be anything)
    type: cpu
    num_threads: 3

go2rtc:
  streams:
    vzhodni_blok: http://172.17.1.19:8080/video_feed_0

cameras:
  vzhodni_blok:
    ffmpeg:
      inputs:
        - path: http://172.17.1.19:8080/video_feed_0
          input_args: preset-http-mjpeg-generic
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/vzhodni_blok
          input_args: preset-rtsp-generic
          roles:
            - record

version: 0.14
```
